"""
SpecWriterAgent
---------------
Responsible for merging the LLM-generated examples back into the original
OpenAPI specification and writing the enriched spec to a new JSON file.
The output file is saved in the same directory as the original, with a
timestamp suffix appended to the original filename.

When --api-src is provided, endpoints that exist only in the implementation
(MISSING_IN_SPEC) are inserted into the paths dict before example merging,
so the final spec is 100% aligned with the source code.
"""

import copy
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from src.models.openapi_models import EndpointInfo
from src.utils.config import Config
from src.utils.logger import setup_logger

logger = setup_logger("spec_writer_agent")


class SpecWriterAgent:
    """
    Agent that merges enrichment data into the original OpenAPI spec
    and persists the improved specification to disk.

    Version-aware: detects whether the original spec is Swagger 2.0 or
    OpenAPI 3.x and uses the appropriate structure for inserting examples.
    """

    def __init__(self, original_spec: Dict[str, Any], spec_path: Path) -> None:
        self.original_spec = original_spec
        self.spec_path = spec_path
        # Detect the spec version from the document itself
        detected = Config.detect_spec_version(original_spec)
        self._spec_major_version: int = int(detected.split(".")[0]) if detected else 3
        logger.info(
            "SpecWriterAgent: detected spec version '%s' (major=%d)",
            detected or "unknown",
            self._spec_major_version,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def merge_examples(
        self,
        enrichments: List[Tuple[EndpointInfo, Dict[str, Any]]],
    ) -> Dict[str, Any]:
        """
        Deep-copy the original spec and inject examples from the enrichment data.

        Steps performed:
        1. For every endpoint marked as impl-only (_impl_only=True), create a
           minimal but valid OpenAPI path/operation entry in the paths dict so
           that subsequent example injection can find it.
        2. For every endpoint with _impl_retcodes_replacing_default set, expand
           the 'default' response entry into individual entries for each real
           retcode extracted from the implementation.
        3. Inject parameter examples, request body examples, and response body
           examples generated by the LLM into each operation.

        Returns the enriched spec dict.
        """
        enriched = copy.deepcopy(self.original_spec)
        paths = enriched.setdefault("paths", {})

        # ----------------------------------------------------------------
        # Pass 1: Insert impl-only endpoints into the paths dict
        # ----------------------------------------------------------------
        for endpoint, _examples in enrichments:
            if not getattr(endpoint, "_impl_only", False):
                continue
            path = endpoint.path
            method = endpoint.method.lower()

            # Ensure the path key exists
            if path not in paths:
                paths[path] = {}

            # Only insert if the method is not already present
            if method not in paths[path]:
                operation = self._build_minimal_operation(endpoint)
                paths[path][method] = operation
                logger.info(
                    "Inserted impl-only endpoint into spec: %s %s",
                    endpoint.method,
                    endpoint.path,
                )

        # ----------------------------------------------------------------
        # Pass 2: Merge examples into all endpoints (original + impl-only)
        # ----------------------------------------------------------------
        for endpoint, examples in enrichments:
            path = endpoint.path
            method = endpoint.method.lower()

            if path not in paths:
                logger.warning(
                    "Path '%s' not found in spec during merge. Skipping.", path
                )
                continue

            operation: Dict[str, Any] = paths[path].get(method, {})
            if not operation:
                logger.warning(
                    "Method '%s' not found for path '%s' during merge. Skipping.",
                    method,
                    path,
                )
                continue

            param_examples: Dict[str, Any] = examples.get("parameters_examples", {})
            req_body_examples: Dict[str, Any] = examples.get("request_body_examples", {})
            response_body_examples: Dict[str, Any] = examples.get(
                "response_body_examples", {}
            )

            # ---- Align responses dict with impl retcodes ----
            responses: Dict[str, Any] = operation.setdefault("responses", {})

            # Case A: spec used 'default'; expand it into real impl error codes
            impl_retcodes: List[str] = getattr(
                endpoint, "_impl_retcodes_replacing_default", []
            )
            if impl_retcodes and "default" in responses:
                default_template = copy.deepcopy(responses["default"])
                del responses["default"]
                for real_code in impl_retcodes:
                    if real_code not in responses:
                        code_int = int(real_code) if real_code.isdigit() else 0
                        if code_int in (200, 201, 204):
                            desc = "Successful response"
                        elif 400 <= code_int < 500:
                            desc = f"Client error — {real_code}"
                        elif 500 <= code_int < 600:
                            desc = f"Server error — {real_code}"
                        else:
                            desc = default_template.get("description", real_code)
                        new_entry = copy.deepcopy(default_template)
                        new_entry["description"] = desc
                        responses[real_code] = new_entry
                        logger.debug(
                            "Expanded 'default' → '%s' for %s %s",
                            real_code,
                            endpoint.method,
                            endpoint.path,
                        )
                logger.info(
                    "[Case A] Replaced 'default' with explicit codes %s for %s %s",
                    impl_retcodes,
                    endpoint.method,
                    endpoint.path,
                )

            # Case B: spec had explicit retcodes different from impl; replace entirely
            impl_full_replace: List[str] = getattr(
                endpoint, "_impl_retcodes_full_replace", []
            )
            if impl_full_replace:
                impl_codes_set = set(str(c) for c in impl_full_replace)
                spec_codes_set = set(responses.keys())
                # Remove retcodes that exist only in the spec (not in impl)
                for spec_only_code in spec_codes_set - impl_codes_set:
                    del responses[spec_only_code]
                    logger.debug(
                        "[Case B] Removed spec-only retcode '%s' from %s %s",
                        spec_only_code, endpoint.method, endpoint.path,
                    )
                # Add retcodes that exist only in the impl (not yet in spec)
                for impl_only_code in impl_codes_set - spec_codes_set:
                    code_int = int(impl_only_code) if impl_only_code.isdigit() else 0
                    if code_int in (200, 201, 204):
                        desc = "Successful response"
                    elif 400 <= code_int < 500:
                        desc = f"Client error — {impl_only_code}"
                    elif 500 <= code_int < 600:
                        desc = f"Server error — {impl_only_code}"
                    elif code_int == 405:
                        desc = "Method not allowed"
                    else:
                        desc = f"Response {impl_only_code}"
                    responses[impl_only_code] = {"description": desc}
                    logger.debug(
                        "[Case B] Added impl-only retcode '%s' to %s %s",
                        impl_only_code, endpoint.method, endpoint.path,
                    )
                logger.info(
                    "[Case B] Responses aligned with impl for %s %s: now %s",
                    endpoint.method, endpoint.path, sorted(responses.keys()),
                )

            # ---- Compute the set of valid response codes after all alignment ----
            # This is the authoritative set used to filter LLM-generated examples,
            # preventing phantom codes (e.g. 401/403/404 invented by the LLM) from
            # being written into x-parameter-examples or response body examples.
            valid_response_codes: set = set(responses.keys())

            # ---- Force required:true for all in:path parameters ----
            for param in operation.get("parameters", []):
                if isinstance(param, dict) and param.get("in") == "path":
                    if not param.get("required", False):
                        param["required"] = True
                        logger.debug(
                            "Set required=true for path param '%s' in %s %s",
                            param.get("name"), endpoint.method, endpoint.path,
                        )

            # ---- Enrich parameters ----
            if param_examples and operation.get("parameters"):
                # --- FIX: discard any response-code key that the LLM invented
                # but that does not actually exist in this operation's responses.
                # This prevents phantom 401/403/404 examples from leaking into
                # the spec when the implementation never emits those codes.
                param_examples = {
                    code: val
                    for code, val in param_examples.items()
                    if str(code) in valid_response_codes
                }
                phantom_keys = set(param_examples) - valid_response_codes  # already empty after filter, kept for logging
                if phantom_keys:
                    logger.warning(
                        "Discarded phantom x-parameter-examples keys %s for %s %s "
                        "(not present in operation responses).",
                        sorted(phantom_keys), endpoint.method, endpoint.path,
                    )

                if param_examples:
                    # Set the scalar 'example' field on each parameter using the
                    # first 'typical' (or first available) example for the first
                    # success code — this keeps Swagger UI / editor previews working.
                    first_success_code = next(
                        (c for c in param_examples if str(c).startswith("2")),
                        next(iter(param_examples), None),
                    )
                    if first_success_code:
                        examples_list = param_examples[first_success_code]
                        # Pick the example named 'typical', or fall back to the first one
                        if isinstance(examples_list, list) and examples_list:
                            typical = next(
                                (e for e in examples_list if e.get("_name") == "typical"),
                                examples_list[0],
                            )
                            for param in operation["parameters"]:
                                param_name = param.get("name")
                                if param_name and param_name in typical:
                                    param["example"] = typical[param_name]
                        elif isinstance(examples_list, dict):
                            # Backward-compat: single dict (no _name)
                            for param in operation["parameters"]:
                                param_name = param.get("name")
                                if param_name and param_name in examples_list:
                                    param["example"] = examples_list[param_name]
                    # Store the filtered multi-example structure as x-parameter-examples
                    operation["x-parameter-examples"] = param_examples
                    logger.debug(
                        "x-parameter-examples written for %s %s — codes: %s",
                        endpoint.method, endpoint.path, sorted(param_examples.keys()),
                    )

            # ---- Enrich request body ----
            if req_body_examples:
                # Filter to valid response codes only
                req_body_examples = {
                    code: val
                    for code, val in req_body_examples.items()
                    if str(code) in valid_response_codes
                }
            if req_body_examples:
                if self._spec_major_version >= 3 and operation.get("requestBody"):
                    # OpenAPI 3.x: examples go inside requestBody.content.<media>.examples
                    content = operation["requestBody"].get("content", {})
                    for _media_type, media_obj in content.items():
                        if isinstance(media_obj, dict):
                            merged: Dict[str, Any] = {}
                            for code, val in req_body_examples.items():
                                if not val:
                                    continue
                                if isinstance(val, list):
                                    # New format: list of named examples
                                    for ex in val:
                                        name = ex.get("_name", "example")
                                        body_val = ex.get("value", {k: v for k, v in ex.items() if k != "_name"})
                                        merged[f"{code}_{name}"] = {"value": body_val}
                                else:
                                    # Old format: single dict
                                    merged[f"example_{code}"] = {"value": val}
                            media_obj["examples"] = merged
                elif self._spec_major_version < 3:
                    # Swagger 2.0: body parameters carry examples via x-examples extension
                    for param in operation.get("parameters", []):
                        if isinstance(param, dict) and param.get("in") == "body":
                            merged_v2: Dict[str, Any] = {}
                            for code, val in req_body_examples.items():
                                if not val:
                                    continue
                                if isinstance(val, list):
                                    for ex in val:
                                        name = ex.get("_name", "example")
                                        body_val = ex.get("value", {k: v for k, v in ex.items() if k != "_name"})
                                        merged_v2[f"{code}_{name}"] = {"value": body_val}
                                else:
                                    merged_v2[f"example_{code}"] = {"value": val}
                            param["x-examples"] = merged_v2

            # ---- Enrich responses ----
            for code, response_obj in responses.items():
                if not isinstance(response_obj, dict):
                    continue
                example_value = response_body_examples.get(str(code))
                if example_value is None:
                    example_value = response_body_examples.get("default")

                if example_value is not None:
                    if self._spec_major_version >= 3:
                        # OpenAPI 3.x: examples go inside responses.<code>.content.<media>.examples
                        content = response_obj.get("content")
                        if content:
                            for _media_type, media_obj in content.items():
                                if isinstance(media_obj, dict):
                                    media_obj["examples"] = {
                                        f"example_{code}": {"value": example_value}
                                    }
                        else:
                            response_obj["content"] = {
                                "application/json": {
                                    "examples": {
                                        f"example_{code}": {"value": example_value}
                                    }
                                }
                            }
                    else:
                        # Swagger 2.0: examples go directly in responses.<code>.examples
                        # keyed by media type (e.g. "application/json")
                        existing_examples = response_obj.get("examples", {})
                        existing_examples["application/json"] = example_value
                        response_obj["examples"] = existing_examples

            logger.debug(
                "Merged examples for endpoint: %s %s", endpoint.method, endpoint.path
            )

        logger.info("All enrichments merged into the specification.")
        return enriched

    def write(
        self, enriched_spec: Dict[str, Any], timestamp: Optional[str] = None
    ) -> Path:
        """
        Write the enriched spec to a new file in the same directory as the original.
        The filename follows the pattern: <original_stem>_<timestamp>.json

        Returns the path to the written file.
        """
        if timestamp is None:
            timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        output_filename = f"{self.spec_path.stem}_{timestamp}.json"
        output_path = self.spec_path.parent / output_filename

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(enriched_spec, f, indent=2, ensure_ascii=False)

        logger.info("Enriched specification written to: %s", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_minimal_operation(endpoint: EndpointInfo) -> Dict[str, Any]:
        """
        Build a minimal but valid OpenAPI operation object for an impl-only endpoint.
        This provides a proper scaffold that subsequent example injection can populate.
        """
        # Build parameters list
        parameters: List[Dict[str, Any]] = []
        for param in (endpoint.parameters or []):
            if isinstance(param, dict):
                # Already a dict — use as-is, ensuring required fields exist
                p = dict(param)
                p.setdefault("in", "query")
                p.setdefault("schema", {"type": "string"})
                # OpenAPI rule: in:path parameters MUST have required:true
                if p.get("in") == "path":
                    p["required"] = True
                parameters.append(p)
            else:
                parameters.append({
                    "name": str(param),
                    "in": "query",
                    "schema": {"type": "string"},
                })

        # Build responses dict
        responses: Dict[str, Any] = {}
        for code in (endpoint.response_codes or ["200"]):
            code_int = int(code) if str(code).isdigit() else 0
            if code_int == 200 or code_int == 201 or code_int == 204:
                desc = "Successful response"
            elif 400 <= code_int < 500:
                desc = f"Client error — {code}"
            elif 500 <= code_int < 600:
                desc = f"Server error — {code}"
            elif code_int == 405:
                desc = "Method not allowed"
            else:
                desc = f"Response {code}"
            responses[str(code)] = {"description": desc}

        operation: Dict[str, Any] = {
            "summary": endpoint.summary or f"{endpoint.method} {endpoint.path}",
            "description": endpoint.description or (
                f"Endpoint found in implementation but absent from the original spec. "
                f"Added automatically by OpenAPI Spec Improver."
            ),
            "responses": responses,
            "x-added-from-impl": True,
        }
        if parameters:
            operation["parameters"] = parameters
        if endpoint.request_body:
            operation["requestBody"] = endpoint.request_body

        return operation
