"""
SpecWriterAgent
---------------
Responsible for merging the LLM-generated examples back into the original
OpenAPI specification and writing the enriched spec to a new JSON file.
The output file is saved in the same directory as the original, with a
timestamp suffix appended to the original filename.

When --api-src is provided, endpoints that exist only in the implementation
(MISSING_IN_SPEC) are inserted into the paths dict before example merging,
so the final spec is 100% aligned with the source code.
"""

import copy
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from src.models.openapi_models import EndpointInfo
from src.utils.logger import setup_logger

logger = setup_logger("spec_writer_agent")


class SpecWriterAgent:
    """
    Agent that merges enrichment data into the original OpenAPI spec
    and persists the improved specification to disk.
    """

    def __init__(self, original_spec: Dict[str, Any], spec_path: Path,
                 spec_version: Optional[str] = None) -> None:
        self.original_spec = original_spec
        self.spec_path = spec_path
        # Detect major version from the spec itself, falling back to the argument.
        raw_version = original_spec.get("openapi") or original_spec.get("swagger", "3.0")
        detected = str(spec_version or raw_version)
        try:
            self.spec_major_version: int = int(detected.split(".")[0])
        except (ValueError, IndexError):
            self.spec_major_version = 3
        logger.info("SpecWriterAgent: operating in OpenAPI %s mode.", detected)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def merge_examples(
        self,
        enrichments: List[Tuple[EndpointInfo, Dict[str, Any]]],
    ) -> Dict[str, Any]:
        """
        Deep-copy the original spec and inject examples from the enrichment data.

        Steps performed:
        1. For every endpoint marked as impl-only (_impl_only=True), create a
           minimal but valid OpenAPI path/operation entry in the paths dict so
           that subsequent example injection can find it.
        2. For every endpoint with _impl_retcodes_replacing_default set, expand
           the 'default' response entry into individual entries for each real
           retcode extracted from the implementation.
        3. Inject parameter examples, request body examples, and response body
           examples generated by the LLM into each operation.

        Returns the enriched spec dict.
        """
        enriched = copy.deepcopy(self.original_spec)
        paths = enriched.setdefault("paths", {})

        # ----------------------------------------------------------------
        # Pass 1: Insert impl-only endpoints into the paths dict
        # ----------------------------------------------------------------
        for endpoint, _examples in enrichments:
            if not getattr(endpoint, "_impl_only", False):
                continue
            path = endpoint.path
            method = endpoint.method.lower()

            # Ensure the path key exists
            if path not in paths:
                paths[path] = {}

            # Only insert if the method is not already present
            if method not in paths[path]:
                operation = self._build_minimal_operation(endpoint)
                paths[path][method] = operation
                logger.info(
                    "Inserted impl-only endpoint into spec: %s %s",
                    endpoint.method,
                    endpoint.path,
                )

        # ----------------------------------------------------------------
        # Pass 2: Merge examples into all endpoints (original + impl-only)
        # ----------------------------------------------------------------
        for endpoint, examples in enrichments:
            path = endpoint.path
            method = endpoint.method.lower()

            if path not in paths:
                logger.warning(
                    "Path '%s' not found in spec during merge. Skipping.", path
                )
                continue

            operation: Dict[str, Any] = paths[path].get(method, {})
            if not operation:
                logger.warning(
                    "Method '%s' not found for path '%s' during merge. Skipping.",
                    method,
                    path,
                )
                continue

            param_examples: Dict[str, Any] = examples.get("parameters_examples", {})
            req_body_examples: Dict[str, Any] = examples.get("request_body_examples", {})
            response_body_examples: Dict[str, Any] = examples.get(
                "response_body_examples", {}
            )

            # ---- Expand 'default' into real retcodes (when impl provides them) ----
            impl_retcodes: List[str] = getattr(
                endpoint, "_impl_retcodes_replacing_default", []
            )
            responses: Dict[str, Any] = operation.setdefault("responses", {})
            if impl_retcodes and "default" in responses:
                default_template = copy.deepcopy(responses["default"])
                del responses["default"]
                for real_code in impl_retcodes:
                    if real_code not in responses:
                        code_int = int(real_code) if real_code.isdigit() else 0
                        if 400 <= code_int < 500:
                            desc = f"Client error — {real_code}"
                        elif 500 <= code_int < 600:
                            desc = f"Server error — {real_code}"
                        else:
                            desc = default_template.get("description", real_code)
                        new_entry = copy.deepcopy(default_template)
                        new_entry["description"] = desc
                        responses[real_code] = new_entry
                        logger.debug(
                            "Expanded 'default' → '%s' for %s %s",
                            real_code,
                            endpoint.method,
                            endpoint.path,
                        )
                logger.info(
                    "Replaced 'default' with explicit codes %s for %s %s",
                    impl_retcodes,
                    endpoint.method,
                    endpoint.path,
                )

            # ---- Enrich parameters ----
            if param_examples and operation.get("parameters"):
                first_code = next(iter(param_examples), None)
                if first_code:
                    code_param_examples = param_examples[first_code]
                    for param in operation["parameters"]:
                        param_name = param.get("name")
                        if param_name and param_name in code_param_examples:
                            if self.spec_major_version >= 3:
                                # OAS 3.x: 'example' is a valid parameter field.
                                param["example"] = code_param_examples[param_name]
                            # Swagger 2.0: 'example' is NOT in the parameter
                            # sub-schemas (additionalProperties: false) — skip
                            # inline injection to keep the spec valid.
                # Always store the full example map as a vendor extension so
                # tooling can consume it regardless of spec version.
                operation["x-parameter-examples"] = param_examples

            # ---- Enrich request body ----
            # OAS 3.x: requestBody is a first-class field.
            # Swagger 2.0: there is no requestBody — body parameters were already
            # represented as formData/body parameters and are handled via
            # x-parameter-examples. Nothing to inject here for 2.0.
            if req_body_examples and self.spec_major_version >= 3 and operation.get("requestBody"):
                content = operation["requestBody"].get("content", {})
                for _media_type, media_obj in content.items():
                    if isinstance(media_obj, dict):
                        media_obj["examples"] = {
                            f"example_{code}": {"value": val}
                            for code, val in req_body_examples.items()
                            if val
                        }

            # ---- Enrich responses ----
            for code, response_obj in responses.items():
                if not isinstance(response_obj, dict):
                    continue
                example_value = response_body_examples.get(str(code))
                if example_value is None:
                    example_value = response_body_examples.get("default")

                if example_value is not None:
                    if self.spec_major_version >= 3:
                        # OAS 3.x: examples go inside response.content.<media_type>.examples
                        content = response_obj.get("content")
                        if content:
                            for _media_type, media_obj in content.items():
                                if isinstance(media_obj, dict):
                                    media_obj["examples"] = {
                                        f"example_{code}": {"value": example_value}
                                    }
                        else:
                            response_obj["content"] = {
                                "application/json": {
                                    "examples": {
                                        f"example_{code}": {"value": example_value}
                                    }
                                }
                            }
                    else:
                        # Swagger 2.0: the response object has no 'content' field.
                        # Store examples as a vendor extension (x-examples) so the
                        # document stays valid against the Swagger 2.0 schema.
                        response_obj.setdefault("x-examples", {})[
                            f"example_{code}"
                        ] = {"value": example_value}

            logger.debug(
                "Merged examples for endpoint: %s %s", endpoint.method, endpoint.path
            )

        logger.info("All enrichments merged into the specification.")
        return enriched

    def write(
        self, enriched_spec: Dict[str, Any], timestamp: Optional[str] = None
    ) -> Path:
        """
        Write the enriched spec to a new file in the same directory as the original.
        The filename follows the pattern: <original_stem>_<timestamp>.json

        Returns the path to the written file.
        """
        if timestamp is None:
            timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        output_filename = f"{self.spec_path.stem}_{timestamp}.json"
        output_path = self.spec_path.parent / output_filename

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(enriched_spec, f, indent=2, ensure_ascii=False)

        logger.info("Enriched specification written to: %s", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_minimal_operation(endpoint: EndpointInfo) -> Dict[str, Any]:
        """
        Build a minimal but valid OpenAPI operation object for an impl-only endpoint.
        This provides a proper scaffold that subsequent example injection can populate.
        """
        # Build parameters list
        parameters: List[Dict[str, Any]] = []
        for param in (endpoint.parameters or []):
            if isinstance(param, dict):
                # Already a dict — use as-is, ensuring required fields exist
                p = dict(param)
                p.setdefault("in", "query")
                p.setdefault("schema", {"type": "string"})
                parameters.append(p)
            else:
                parameters.append({
                    "name": str(param),
                    "in": "query",
                    "schema": {"type": "string"},
                })

        # Build responses dict
        responses: Dict[str, Any] = {}
        for code in (endpoint.response_codes or ["200"]):
            code_int = int(code) if str(code).isdigit() else 0
            if code_int == 200 or code_int == 201 or code_int == 204:
                desc = "Successful response"
            elif 400 <= code_int < 500:
                desc = f"Client error — {code}"
            elif 500 <= code_int < 600:
                desc = f"Server error — {code}"
            elif code_int == 405:
                desc = "Method not allowed"
            else:
                desc = f"Response {code}"
            responses[str(code)] = {"description": desc}

        operation: Dict[str, Any] = {
            "summary": endpoint.summary or f"{endpoint.method} {endpoint.path}",
            "description": endpoint.description or (
                f"Endpoint found in implementation but absent from the original spec. "
                f"Added automatically by OpenAPI Spec Improver."
            ),
            "responses": responses,
            "x-added-from-impl": True,
        }
        if parameters:
            operation["parameters"] = parameters
        if endpoint.request_body:
            operation["requestBody"] = endpoint.request_body

        return operation
